### ISSUE TITLE
Add repo.json file

### ISSUE THREAD

**Issue by Norsze** [Kareadita/tach-extension#3]
### Describe why this should be added

It will be required in the future and is already needed in the beta build of some of the apps forked from Tachiyomi.

### Other details

![image](https://github.com/Kareadita/tach-extension/assets/66540317/25ce6ad8-b4ac-4726-9a7e-b4c74360ee34)
![image](https://github.com/Kareadita/tach-extension/assets/66540317/d49a48c4-721e-49cd-abd2-9badf2082300)
![image](https://github.com/Kareadita/tach-extension/assets/66540317/74ee425a-efbf-434f-a85d-23f2258d66df)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by majora2007** [comment]
Thanks for the heads up. We can work on getting this setup.

**Comment by majora2007** [comment]
Where are you seeing this posted in discord? I joined Mihon discord and do not see these messages.

**Comment by majora2007** [comment]
Thanks

**Comment by ThePromidius** [comment]
Guess [b2a0027](https://github.com/Kareadita/tach-extension/commit/b2a0027036f15b157d8bb677d3e1f10096242b4d) will do?
Closing issue for now. Let me know if it works.

**Comment by ThePromidius** [comment]
Actually pushed to the wrong repo. [b2a0027](https://github.com/Kareadita/tachiyomi-extensions/commit/b2a0027036f15b157d8bb677d3e1f10096242b4d) Should do
